companieshouse/company-appointments.api.ch.gov.uk

- src/it/java/uk/gov/companieshouse/company_appointments/CompanyAppointmentControllerITest.java
- src/main/java/uk/gov/companieshouse/company_appointments/CompanyAppointmentMapper.java
- src/main/java/uk/gov/companieshouse/company_appointments/model/view/CompanyAppointmentView.java
- src/main/java/uk/gov/companieshouse/company_appointments/model/view/DateOfBirth.java
- src/test/java/uk/gov/companieshouse/company_appointments/CompanyAppointmentMapperTest.java
* Hide time from appointment/resignation date and hide day by default in date of birth view object.
> SAPI-412 Appointment/resignation date should not contain time; only display month + year in DOB

- src/it/java/uk/gov/companieshouse/company_appointments/AuthenticationInterceptorsIT.java
- src/main/java/uk/gov/companieshouse/company_appointments/config/Config.java
- src/main/java/uk/gov/companieshouse/company_appointments/interceptor/AuthenticationHelper.java
- src/main/java/uk/gov/companieshouse/company_appointments/interceptor/AuthenticationHelperImpl.java
- src/main/java/uk/gov/companieshouse/company_appointments/interceptor/FullRecordAuthenticationInterceptor.java
- src/test/java/uk/gov/companieshouse/company_appointments/config/ConfigTest.java
- src/test/java/uk/gov/companieshouse/company_appointments/interceptor/AuthenticationHelperImplTest.java
- src/test/java/uk/gov/companieshouse/company_appointments/interceptor/FullRecordAuthenticationInterceptorTest.java
- add auth interceptor for 'full_record' path GET and PUT
NOTE:
officer-delta-processor and manual requests must now use a CHS key with `internal_app_privileges:true`
> Add authentication on endpoint to return officer data

- src/main/java/uk/gov/companieshouse/company_appointments/interceptor/AuthenticationHelper.java
- src/main/java/uk/gov/companieshouse/company_appointments/interceptor/AuthenticationHelperImpl.java
- src/main/java/uk/gov/companieshouse/company_appointments/interceptor/FullRecordAuthenticationInterceptor.java
- src/test/java/uk/gov/companieshouse/company_appointments/interceptor/AuthenticationHelperImplTest.java
- src/test/java/uk/gov/companieshouse/company_appointments/interceptor/FullRecordAuthenticationInterceptorTest.java
FullRecordAuthenticationInterceptor checks if the incoming request has internal api privileges with the depreciated `ERIC-Authorised-Key-Roles` header. This PR replaces it with the `ERIC-Authorised-Key-Privileges`.
> Replaced depreciated eric auth header

- pom.xml
* Upgrade Log4J to v2.16.0
* Upgrade CH structured-logging to v1.9.11
[dependency-tree.txt](https://github.com/companieshouse/company-appointments.api.ch.gov.uk/files/7718862/dependency-tree.txt)
> Resolve Log4Shell security issue

- pom.xml
- src/it/java/uk/gov/companieshouse/company_appointments/AuthenticationInterceptorsITest.java
- src/main/java/uk/gov/companieshouse/company_appointments/CompanyAppointmentFullRecordService.java
- src/main/java/uk/gov/companieshouse/company_appointments/model/data/AppointmentApiEntity.java
- src/main/java/uk/gov/companieshouse/company_appointments/model/view/CompanyAppointmentFullRecordView.java
- src/test/java/uk/gov/companieshouse/company_appointments/AppointmentApiRepositoryTest.java
- src/test/java/uk/gov/companieshouse/company_appointments/CompanyAppointmentFullRecordServiceTest.java
- src/test/java/uk/gov/companieshouse/company_appointments/model/view/CompanyAppointmentFullRecordViewTest.java
This PR allows the sensitive data block coming from the officer delta processor to be saved and the get to still show the items as part of the full record view.
**Resolves**
DSND-1246
> initial commit save new sensitive data block from processor

- src/main/java/uk/gov/companieshouse/company_appointments/interceptor/AuthenticationHelper.java
- src/main/java/uk/gov/companieshouse/company_appointments/interceptor/AuthenticationHelperImpl.java
- src/main/java/uk/gov/companieshouse/company_appointments/interceptor/FullRecordAuthenticationInterceptor.java
- src/test/java/uk/gov/companieshouse/company_appointments/interceptor/AuthenticationHelperImplTest.java
- src/test/java/uk/gov/companieshouse/company_appointments/interceptor/FullRecordAuthenticationInterceptorTest.java
This pr adds an OAuth2 authentication route for the full_record request. The OAuth2 token is checked for the company_officers read-protected permission and whether the user is logged into the correct company.
**Resolves:**
- DSND-1240
> Add OAuth2 authorisation to the full_record request

- src/main/java/uk/gov/companieshouse/company_appointments/interceptor/AuthenticationHelperImpl.java
- src/test/java/uk/gov/companieshouse/company_appointments/interceptor/AuthenticationHelperImplTest.java
This PR adds a ternary check to the api key check to allow put requests to still use an internal privilege key but force the GET request to use a new sensitive data type key.
**Resolves**
DSND-1241
> Add sensitive data check to get request

- src/main/java/uk/gov/companieshouse/company_appointments/CompanyAppointmentFullRecordRepository.java
- src/main/java/uk/gov/companieshouse/company_appointments/CompanyAppointmentFullRecordService.java
- src/test/java/uk/gov/companieshouse/company_appointments/CompanyAppointmentFullRecordServiceTest.java
This PR is to fix the GET full record request in the API to also search mongo records for the company number as well as the appointment id.
**Resolves**
- DSND-1286
> Read appointment id and company number on GET request

- pom.xml
- src/main/java/uk/gov/companieshouse/company_appointments/model/view/CompanyAppointmentFullRecordView.java
This pr updates the sdk to include the company name field when officer data is saved to mongo. The company name field is also fed into the name property that is sent in GET requests.
**Required for:**
-DSND-1307
> Set name to company name for corporate officers

- src/it/java/uk/gov/companieshouse/company_appointments/CompanyAppointmentFullRecordControllerITest.java
- src/main/java/uk/gov/companieshouse/company_appointments/CompanyAppointmentFullRecordController.java
- src/main/java/uk/gov/companieshouse/company_appointments/CompanyAppointmentFullRecordRepository.java
- src/main/java/uk/gov/companieshouse/company_appointments/CompanyAppointmentFullRecordService.java
- src/main/java/uk/gov/companieshouse/company_appointments/config/Config.java
- src/main/java/uk/gov/companieshouse/company_appointments/interceptor/AuthenticationHelperImpl.java
- src/test/java/uk/gov/companieshouse/company_appointments/CompanyAppointmentFullRecordControllerTest.java
- src/test/java/uk/gov/companieshouse/company_appointments/CompanyAppointmentFullRecordServiceTest.java
- src/test/resources/delta-appointment-data.json
This pr adds a delete endpoint to company appointments for the full record request. When called the record is deleted. If the record does not exist a 404 response is sent. Includes a fix to the authenticator for DELETE requests and integration tests.
**Resolves:**
- DSND-1316
> Add delete endpoint for the full record request

- routes.yaml
- src/it/java/uk/gov/companieshouse/company_appointments/CompanyAppointmentControllerITest.java
- src/main/java/uk/gov/companieshouse/company_appointments/CompanyAppointmentComparator.java
- src/main/java/uk/gov/companieshouse/company_appointments/CompanyAppointmentController.java
- src/main/java/uk/gov/companieshouse/company_appointments/CompanyAppointmentRepository.java
- src/main/java/uk/gov/companieshouse/company_appointments/CompanyAppointmentService.java
- src/main/java/uk/gov/companieshouse/company_appointments/model/view/AllCompanyAppointmentsView.java
- src/main/java/uk/gov/companieshouse/company_appointments/model/view/CompanyAppointmentView.java
- src/test/java/uk/gov/companieshouse/company_appointments/CompanyAppointmentComparatorTest.java
- src/test/java/uk/gov/companieshouse/company_appointments/CompanyAppointmentControllerTest.java
- src/test/java/uk/gov/companieshouse/company_appointments/CompanyAppointmentServiceTest.java
- src/test/resources/appointment-data2.json
Added new endpoint for company officers in company_appointments_api.
Added the sorting points: resigned/not resigned, secretary/directors, alphabetical order.
Added getmapping in CompanyAppointmentController.
Added queries in CompanyAppointmentRepository.
Added sort and filter by active officers in CompanyAppointmentService.
Added integration test.
Resolves:
-DSND-1329 https://companieshouse.atlassian.net/browse/DSND-1329
> Create Endpoint for all Company Officers

- src/main/java/uk/gov/companieshouse/company_appointments/SortMapper.java
- src/test/java/uk/gov/companieshouse/company_appointments/SortMapperTest.java
This pr fixes ordering for the default and surname order by options. Natural officers will now be ordered before corporate officers in the list, to match the api.ch.gov.uk solution.
The order "data.company_name", "data.surname" is used as the order direction is ascending and null values come at the top, so null company_names (naturals) will come first.
**Required for**
- DSND-1359
> order natural before corporate officers

- src/main/java/uk/gov/companieshouse/company_appointments/CompanyAppointmentMapper.java
- src/main/java/uk/gov/companieshouse/company_appointments/model/data/OfficerData.java
- src/main/java/uk/gov/companieshouse/company_appointments/model/view/CompanyAppointmentFullRecordView.java
- src/main/java/uk/gov/companieshouse/company_appointments/model/view/CompanyAppointmentView.java
This pr adds individual name fields and the is_pre_1992_appointment flag to the full record GET request. This is to make data work easier in services that call this.
Also added the is_pre_1992_appointment flag to the appointment GET and officer listing get, in order that users know whether to reference appointed_on or appointed_before.
> Add name fields and pre1992 flag to GET requests

- src/main/java/uk/gov/companieshouse/company_appointments/CompanyAppointmentService.java
- src/main/java/uk/gov/companieshouse/company_appointments/model/data/CompanyAppointmentData.java
- src/test/java/uk/gov/companieshouse/company_appointments/CompanyAppointmentMapperTest.java
- src/test/java/uk/gov/companieshouse/company_appointments/CompanyAppointmentServiceTest.java
Added in the new code that will ensure that it Returns the inactive/active count in company/officers GET depending on company status. New code does this a appears correctly.
Added in company_status to CompanyAppointmentData to get the status later on
Changed Tests to ensure they had the status added. and added two new tests to ensure the active and inactive count came out correctly.
> Feature/return inactive/active count in company/officers get depending on company status

- routes.yaml
* Takes in a set number of characters for company_number, rather than any length.
* Changes passed on local dev environment testing.
Resolves [DSND-1454](https://companieshouse.atlassian.net/browse/DSND-1454)
[DSND-1454]: https://companieshouse.atlassian.net/browse/DSND-1454?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DSND-1454 Fix route that conflicts with company-profile-api

- routes.yaml
- src/it/java/uk/gov/companieshouse/company_appointments/CompanyAppointmentControllerITest.java
- src/main/java/uk/gov/companieshouse/company_appointments/CompanyAppointmentController.java
This pr changes the uri for the officer listing endpoint to a test value. This is so when it is released it does not overwrite the current perl url, due to the endpoint not being finished.
> Change officer list endpoint to flag off in the release

- docs/mongo_sort_query.txt
- pom.xml
- src/it/java/uk/gov/companieshouse/company_appointments/CucumberFeaturesRunnerITest.java
- src/it/java/uk/gov/companieshouse/company_appointments/officerappointments/OfficerAppointmentsRepositoryITest.java
- src/it/java/uk/gov/companieshouse/company_appointments/tests/CompanyAppointmentControllerITest.java
- src/main/java/uk/gov/companieshouse/company_appointments/officerappointments/OfficerAppointmentsRepository.java
- src/test/resources/appointment-data.json
- src/test/resources/appointment-data2.json
- src/test/resources/appointment-data4.json
- src/test/resources/appointment-data5.json
- src/test/resources/appointment-data6.json
* Mongo aggregation now sorts by appointed_on/appointed_before (if the former is null) for active roles and resigned_on or resigned roles. Active roles are listed first. All sorted in descending order.
* Updated the integration test to test the mongo aggregation. 
* Updated the id of a test appointments data json files to make the repository itest easier to organise and read. This broke one other itest - simple fix was to update the broken itest with the new id string - see `CompanyAppointmentControllerItest`.
* The reason for testing five documents in the repository itest was because I needed at least two valid active and two valid resigned roles to test plus a third valid active role that had an `appointed_before` field and did not have an `appointed_on` field as per the acceptance …
> DSND-1447 Implement officer appointment list sorting

- docs/mongo_sort_with_filter_aggregation.txt
- src/it/java/uk/gov/companieshouse/company_appointments/officerappointments/OfficerAppointmentsRepositoryITest.java
- src/main/java/uk/gov/companieshouse/company_appointments/officerappointments/OfficerAppointmentsMapper.java
- src/main/java/uk/gov/companieshouse/company_appointments/officerappointments/OfficerAppointmentsRepository.java
- src/main/java/uk/gov/companieshouse/company_appointments/officerappointments/OfficerAppointmentsService.java
- src/test/java/uk/gov/companieshouse/company_appointments/officerappointments/OfficerAppointmentsMapperTest.java
- src/test/java/uk/gov/companieshouse/company_appointments/officerappointments/OfficerAppointmentsServiceTest.java
* Update aggregation query to slice the result set using the paging parameters if specified, otherwise, defaults to 0 and 35.
* Update mapper to set start index and items per page in the response body.
[DSND-1449](https://companieshouse.atlassian.net/browse/DSND-1449)
[DSND-1449]: https://companieshouse.atlassian.net/browse/DSND-1449?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DSND-1449 Implement paging for officer appointments list

- src/it/java/uk/gov/companieshouse/company_appointments/officerappointments/OfficerAppointmentsRepositoryITest.java
- src/main/java/uk/gov/companieshouse/company_appointments/officerappointments/OfficerAppointmentsService.java
- src/test/java/uk/gov/companieshouse/company_appointments/officerappointments/OfficerAppointmentsServiceTest.java
* Missed requirement: When the query param `items_per_page` is set to any number above 50, we should revert the items_per_page in java to 50.
* Itest now uses a for loop to add over 50 appointments to an additional officer so we can test the total results and list of appointments size are returned correctly.
* Tested locally.
[DSND-1449](https://companieshouse.atlassian.net/browse/DSND-1449)
[DSND-1449]: https://companieshouse.atlassian.net/browse/DSND-1449?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DSND-1449 Implement pagination when items per page is over 50

- pom.xml
- src/it/java/uk/gov/companieshouse/company_appointments/officerappointments/OfficerAppointmentsRepositoryITest.java
- src/main/java/uk/gov/companieshouse/company_appointments/officerappointments/DateOfBirthMapper.java
- src/main/java/uk/gov/companieshouse/company_appointments/officerappointments/OfficerAppointmentsMapper.java
- src/main/java/uk/gov/companieshouse/company_appointments/officerappointments/OfficerAppointmentsRepository.java
- src/main/java/uk/gov/companieshouse/company_appointments/officerappointments/OfficerAppointmentsService.java
- src/test/java/uk/gov/companieshouse/company_appointments/officerappointments/DateOfBirthMapperTest.java
- src/test/java/uk/gov/companieshouse/company_appointments/officerappointments/OfficerAppointmentsMapperTest.java
- src/test/java/uk/gov/companieshouse/company_appointments/officerappointments/OfficerAppointmentsServiceTest.java
* Change date of birth mapper to return null for coporate officer roles.
* Change pom to use java 11.
* Fetch the first appointment for the given officer id to be used to set top level fields.
* Return empty optional when no appointments are found for the given officer id.
[DSND-1448](https://companieshouse.atlassian.net/browse/DSND-1448)
[DSND-1448]: https://companieshouse.atlassian.net/browse/DSND-1448?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DSND-1448 Implement correct filtering when no active appointments

- pom.xml
- src/it/java/uk/gov/companieshouse/company_appointments/tests/CompanyAppointmentFullRecordRepositoryITest.java
- src/main/java/uk/gov/companieshouse/company_appointments/controller/CompanyAppointmentController.java
- src/main/java/uk/gov/companieshouse/company_appointments/repository/CompanyAppointmentFullRecordRepository.java
- src/main/java/uk/gov/companieshouse/company_appointments/service/CompanyAppointmentService.java
- src/test/java/uk/gov/companieshouse/company_appointments/CompanyAppointmentControllerTest.java
- src/test/java/uk/gov/companieshouse/company_appointments/CompanyAppointmentServiceTest.java
* Mapped HTTP responses codes to exceptions thrown when patching company name and status
* Added a bulk update method to update company name and status in fullRecordAppointmentRepository
* Implemented CompanyAppointmentService.patchCompanyNameStatus
* Updated CompanyAppointmentService logging to use the context ID from the MDC
* Updated dependencies in the pom.xml and removed unused dependencies
[DSND-1531](https://companieshouse.atlassian.net/browse/DSND-1531)
[DSND-1531]: https://companieshouse.atlassian.net/browse/DSND-1531?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DSND-1531: Update company name/status for multiple existing appointments

- src/main/java/uk/gov/companieshouse/company_appointments/mapper/ResourceChangedRequestMapper.java
- src/test/java/uk/gov/companieshouse/company_appointments/ResourceChangedRequestMapperTest.java
The mapper for `ResourceChangedData` was not prepending a slash character when building the `resourceUri`
> DSND-1347: Fixed a missing slash when mapping on the ResourceChangedData.resourceUri

- src/main/java/uk/gov/companieshouse/company_appointments/mapper/CompanyAppointmentMapper.java
- src/test/java/uk/gov/companieshouse/company_appointments/CompanyAppointmentMapperTest.java
* When mapping pre 1992 appts, toLocalDate was being called on the appointed_on field when it was null as these appts don't have an appointed_on date. Fixed this bug by adding a null check in the mapper for the mapping of this field.
[DSND-1599](https://companieshouse.atlassian.net/browse/DSND-1599)
[DSND-1599]: https://companieshouse.atlassian.net/browse/DSND-1599?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DNSD-1599: Fix NullPointerException on appointed_on field

- pom.xml
- src/main/java/uk/gov/companieshouse/company_appointments/api/ResourceChangedApiService.java
- src/main/java/uk/gov/companieshouse/company_appointments/api/ResourceChangedApiServiceAspect.java
- src/main/java/uk/gov/companieshouse/company_appointments/api/StreamEvents.java
- src/main/resources/application.properties
- src/test/java/uk/gov/companieshouse/company_appointments/api/ResourceChangedApiServiceAspectFeatureFlagDisabledITest.java
- src/test/java/uk/gov/companieshouse/company_appointments/api/ResourceChangedApiServiceAspectFeatureFlagEnabledITest.java
- src/test/java/uk/gov/companieshouse/company_appointments/api/ResourceChangedApiServiceAspectTest.java
* Updated versions of CH specific dependencies in Pom.
* Implemented new ResourceChangedApiService Aspect to stop stream events.
* Stream events stopped by ```SEEDING_COLLECTION_ENABLED=true``` the same flag which toggles company name and status.
[DSND-1822](https://companieshouse.atlassian.net/browse/DSND-1822)
[DSND-1822]: https://companieshouse.atlassian.net/browse/DSND-1822?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DSND-1822: Implement feature flag to disable streaming events.

- src/main/java/uk/gov/companieshouse/company_appointments/service/CompanyAppointmentService.java
- src/test/java/uk/gov/companieshouse/company_appointments/service/CompanyAppointmentServiceTest.java
* Etag is being returned on the individual appointment GET endpoint is not being returned in the GET company officer list, this fixes the issue.
[DSND-1970](https://companieshouse.atlassian.net/browse/DSND-1970)
[DSND-1970]: https://companieshouse.atlassian.net/browse/DSND-1970?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DSND-1970: Return etag as a top level field in company officer list

- pom.xml
- src/it/java/uk/gov/companieshouse/company_appointments/tests/CompanyAppointmentControllerITest.java
- src/it/java/uk/gov/companieshouse/company_appointments/tests/CompanyAppointmentFullRecordControllerMongoUnavailableITest.java
- src/main/java/uk/gov/companieshouse/company_appointments/api/CompanyMetricsApiService.java
- src/main/java/uk/gov/companieshouse/company_appointments/api/ResourceChangedApiService.java
- src/main/java/uk/gov/companieshouse/company_appointments/api/ResourceChangedApiServiceAspect.java
- src/main/java/uk/gov/companieshouse/company_appointments/controller/CompanyAppointmentController.java
- src/main/java/uk/gov/companieshouse/company_appointments/controller/CompanyAppointmentFullRecordController.java
- src/main/java/uk/gov/companieshouse/company_appointments/interceptor/AuthenticationInterceptor.java
- src/main/java/uk/gov/companieshouse/company_appointments/interceptor/FullRecordAuthenticationInterceptor.java
- src/main/java/uk/gov/companieshouse/company_appointments/interceptor/RequestLoggingInterceptor.java
- src/main/java/uk/gov/companieshouse/company_appointments/logging/DataMapHolder.java
- src/main/java/uk/gov/companieshouse/company_appointments/mapper/CompanyAppointmentMapper.java
- src/main/java/uk/gov/companieshouse/company_appointments/officerappointments/OfficerAppointmentsController.java
- src/main/java/uk/gov/companieshouse/company_appointments/roles/DirectorRoles.java
- src/main/java/uk/gov/companieshouse/company_appointments/roles/SecretarialRoles.java
- src/main/java/uk/gov/companieshouse/company_appointments/service/CompanyAppointmentFullRecordService.java
- src/main/java/uk/gov/companieshouse/company_appointments/service/CompanyAppointmentService.java
- src/main/java/uk/gov/companieshouse/company_appointments/service/CompanyProfileClient.java
- src/main/java/uk/gov/companieshouse/company_appointments/service/DeltaAppointmentTransformerAspect.java
- src/test/java/uk/gov/companieshouse/company_appointments/CompanyAppointmentFullRecordControllerTest.java
- src/test/java/uk/gov/companieshouse/company_appointments/CompanyProfileClientTest.java
- src/test/java/uk/gov/companieshouse/company_appointments/DeltaAppointmentTransformerAspectTest.java
- src/test/java/uk/gov/companieshouse/company_appointments/api/CompanyMetricsApiServiceTest.java
- src/test/java/uk/gov/companieshouse/company_appointments/api/ResourceChangedApiServiceAspectFeatureFlagDisabledITest.java
- src/test/java/uk/gov/companieshouse/company_appointments/api/ResourceChangedApiServiceTest.java
- src/test/java/uk/gov/companieshouse/company_appointments/model/transformer/DeltaAppointmentTransformerIntegrationTest.java
- src/test/java/uk/gov/companieshouse/company_appointments/officerappointments/OfficerAppointmentsControllerTest.java
- src/test/java/uk/gov/companieshouse/company_appointments/service/CompanyAppointmentFullRecordServiceTest.java
- src/test/java/uk/gov/companieshouse/company_appointments/service/CompanyAppointmentServiceTest.java
* Added a `DataMapHolder` class to store a `DataMapHolder.Builder` instance that captures log data during message processing.
* Added a `String DataMapHolder.getRequestId()` to access the same request ID as used for logging
* Updated the `RequestLoggingInterceptor` to initialise the `DataMapHolder` with the request ID then ensures it is clean when processing is complete.
* Updated all logger calls to include the structured logging `DataMap` content.
The `RequestLoggingInterceptor` replaces the `StructuredLoggingFilter` described in the [Structured Logging](https://companieshouse.atlassian.net/wiki/spaces/TEAM4/pages/4253188169/Adding+Structured+Logging+to+Data+Sync+services) Confluence page. This page will be updated in due course. …
> DSND-1902: Upgrade structured logging

- src/it/java/uk/gov/companieshouse/company_appointments/officerappointments/OfficerAppointmentsControllerITest.java
- src/main/java/uk/gov/companieshouse/company_appointments/interceptor/AuthenticationHelperImpl.java
- src/main/java/uk/gov/companieshouse/company_appointments/officerappointments/ItemsPerPageService.java
- src/main/java/uk/gov/companieshouse/company_appointments/officerappointments/OfficerAppointmentsController.java
- src/main/java/uk/gov/companieshouse/company_appointments/officerappointments/OfficerAppointmentsService.java
- src/main/resources/application.properties
- src/test/java/uk/gov/companieshouse/company_appointments/officerappointments/ItemsPerPageServiceTest.java
- src/test/java/uk/gov/companieshouse/company_appointments/officerappointments/OfficerAppointmentsControllerTest.java
- src/test/java/uk/gov/companieshouse/company_appointments/officerappointments/OfficerAppointmentsServiceTest.java
- src/test/resources/application-feature_flag_enabled.properties
- src/test/resources/application.properties
- src/test/resources/internal-appointment-data.json
This PR changes the logic for calculating the max items per page. When an external GET request hits the API, the max items per page is set to 50, even if the query param is set to above that number. When an internal GET request hits the API, the max items per page is set to 500.
Whether or not the incoming request is external or internal is determined by the request header having a certain string that proves it can only be an internal request.
Tested locally.
[DSND-1968](https://companieshouse.atlassian.net/browse/DSND-1968)
[DSND-1968]: https://companieshouse.atlassian.net/browse/DSND-1968?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DSND-1968: Implement correct items per page for internal get officers list

- src/main/java/uk/gov/companieshouse/company_appointments/config/MongoDbConfig.java
- src/main/java/uk/gov/companieshouse/company_appointments/exception/FailedToTransformException.java
- src/main/java/uk/gov/companieshouse/company_appointments/exception/NotFoundException.java
- src/main/java/uk/gov/companieshouse/company_appointments/exception/ServiceUnavailableException.java
- src/main/java/uk/gov/companieshouse/company_appointments/service/CompanyAppointmentFullRecordService.java
This PR fixes a race condition where resource-change-publisher calls GET on appointments api before the appointment has been persisted to the db. 
Now the full record saves and deletes are transactional, we know that the appointment has been persisted/deleted when the service method completes (i.e., before RCP calls GET).
In order for a transaction to work in the case of a failed transaction (ie. chs-kafka-api is down, and we don't want to save to the db), the exceptions thrown must extend `RuntimeException` rather than `Exception`. We also need to have the database save/delete call before the call to chs-kafka-api.
Tested locally.
[DSND-2041](https://companieshouse.atlassian.net/browse/DSND-2041)
[DSND-2041]: https://companieshouse.atlassian.net/browse/DSND-2041?atlOrigin=eyJpIjoiNWRkNTlj …
> DSND-2041: Add transactional annotation to company appointment full record service

- src/it/java/uk/gov/companieshouse/company_appointments/officerappointments/OfficerAppointmentsControllerITest.java
- src/it/java/uk/gov/companieshouse/company_appointments/officerappointments/OfficerAppointmentsRepositoryITest.java
- src/it/java/uk/gov/companieshouse/company_appointments/tests/CompanyAppointmentRepositoryITest.java
- src/it/resources/application-test.properties
- src/main/java/uk/gov/companieshouse/company_appointments/officerappointments/CompanyAppointmentDocumentId.java
- src/main/java/uk/gov/companieshouse/company_appointments/officerappointments/OfficerAppointmentsAggregate.java
- src/main/java/uk/gov/companieshouse/company_appointments/officerappointments/OfficerAppointmentsMapper.java
- src/main/java/uk/gov/companieshouse/company_appointments/officerappointments/OfficerAppointmentsRepository.java
- src/main/java/uk/gov/companieshouse/company_appointments/officerappointments/OfficerAppointmentsService.java
- src/main/resources/application.properties
- src/test/java/uk/gov/companieshouse/company_appointments/logging/DataMapHolderTest.java
- src/test/java/uk/gov/companieshouse/company_appointments/officerappointments/OfficerAppointmentsMapperTest.java
- src/test/java/uk/gov/companieshouse/company_appointments/officerappointments/OfficerAppointmentsRepositoryTest.java
- src/test/java/uk/gov/companieshouse/company_appointments/officerappointments/OfficerAppointmentsServiceTest.java
- src/test/resources/application.properties
The initial bug was due to an officer having >150K appointments in Staging.
* Added an integration test to the fix exceeds this number with a load of head
* Projects out just the required fields to satisfy the findOfficerAppointments query early in the aggregation pipeline.
* Added a new repository method to return a collection of CompanyAppointmentDocuments given a set of document ids.
room
[DSND-2047](https://companieshouse.atlassian.net/browse/DSND-2047)
[DSND-2047]: https://companieshouse.atlassian.net/browse/DSND-2047?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DSND-2047: Refactor findOfficerAppointments query to handle officers with large numbers of appointments

- src/it/java/uk/gov/companieshouse/company_appointments/officerappointments/OfficerAppointmentsControllerITest.java
Disables a test that create a huge amount of objects. 
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-failsafe-plugin:3.0.0:verify (default) on project company-appointments.api.ch.gov.uk: 
[ERROR] 
[ERROR] Please refer to /tmp/build/5d05d134/source-code/target/failsafe-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] There was an error in the forked process
[ERROR] Java heap space
```
This test can be run locally as required
> DSND-2047: Fix a Java Heap Space error on Concourse pipeline

- src/main/java/uk/gov/companieshouse/company_appointments/service/CompanyAppointmentFullRecordService.java
- src/test/java/uk/gov/companieshouse/company_appointments/CompanyAppointmentControllerTest.java
- src/test/java/uk/gov/companieshouse/company_appointments/CompanyAppointmentFullRecordControllerTest.java
- src/test/java/uk/gov/companieshouse/company_appointments/ResourceChangedRequestMapperTest.java
- src/test/java/uk/gov/companieshouse/company_appointments/SortMapperTest.java
- src/test/java/uk/gov/companieshouse/company_appointments/model/transformer/DeltaIdentificationTransformerTest.java
- src/test/java/uk/gov/companieshouse/company_appointments/model/transformer/DeltaItemLinkTypesTransformerTest.java
- src/test/java/uk/gov/companieshouse/company_appointments/service/CompanyAppointmentFullRecordServiceTest.java
- src/test/java/uk/gov/companieshouse/company_appointments/service/CompanyAppointmentServiceTest.java
* Deleted data is now sent correctly as an OfficerSummary.
* OfficerSummary is serialised and deserialsied an extra time to remove nulls from the Object before the request is sent. This is because the object mapper used in api-sdk-java does not specify NON_NULL serialisation inclusion.
[DSND-2050](https://companieshouse.atlassian.net/browse/DSND-2050)
[DSND-2050]: https://companieshouse.atlassian.net/browse/DSND-2050?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DSND-1520: Fix bug in resource deleted request

- routes.yaml
- src/it/java/uk/gov/companieshouse/company_appointments/officerappointments/OfficerAppointmentsControllerITest.java
- src/it/java/uk/gov/companieshouse/company_appointments/tests/AuthenticationInterceptorsITest.java
- src/it/java/uk/gov/companieshouse/company_appointments/tests/CompanyAppointmentControllerITest.java
- src/it/java/uk/gov/companieshouse/company_appointments/tests/CompanyAppointmentControllerMongoUnavailableITest.java
- src/main/java/uk/gov/companieshouse/company_appointments/controller/CompanyAppointmentController.java
- src/main/java/uk/gov/companieshouse/company_appointments/officerappointments/OfficerAppointmentsController.java
In order for the seeding of the delta_appointments collection in live to go ahead, we need to remove the external get endpoints in this service.
This is so the external GET request will be routed to the Perl services and, therefore, the appointments collection instead of the delta_appointments collection - which will be being seeded.
[DSND-2014](https://companieshouse.atlassian.net/browse/DSND-2014)
[DSND-2014]: https://companieshouse.atlassian.net/browse/DSND-2014?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DSND-2014: Remove external GET endpoints

- routes.yaml
- src/it/java/uk/gov/companieshouse/company_appointments/officerappointments/OfficerAppointmentsControllerITest.java
- src/it/java/uk/gov/companieshouse/company_appointments/tests/AuthenticationInterceptorsITest.java
- src/it/java/uk/gov/companieshouse/company_appointments/tests/CompanyAppointmentControllerITest.java
- src/it/java/uk/gov/companieshouse/company_appointments/tests/CompanyAppointmentControllerMongoUnavailableITest.java
- src/main/java/uk/gov/companieshouse/company_appointments/controller/CompanyAppointmentController.java
- src/main/java/uk/gov/companieshouse/company_appointments/officerappointments/OfficerAppointmentsController.java
Reverts companieshouse/company-appointments.api.ch.gov.uk#132
This is to create another version that will stay in Staging to unblock E2E testing, while the previous version goes through to Live to unblock the trial seeding in the delta_appointments collection.
> Revert "DSND-2014: Remove external GET endpoints"

- routes.yaml
* Changes test whether having two different versions of the same app but with different routes works on Mesos Marathon.
> Change routes to only handle /full_record requests

- routes.yaml
* Reverts routing back to normal working order.
* To be merged once it has been confirmed that our approach of having two different versions of the API works.
> Revert routing back to normal

- src/main/java/uk/gov/companieshouse/company_appointments/config/Config.java
This PR adds additional configuration to the ObjectMapper.
Tested locally.
[DSND-2053](https://companieshouse.atlassian.net/browse/DSND-2053)
[DSND-2053]: https://companieshouse.atlassian.net/browse/DSND-2053?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DSND-2053: Add configuration to ObjectMapper bean

- src/main/java/uk/gov/companieshouse/company_appointments/model/data/DeltaOfficerData.java
- src/main/java/uk/gov/companieshouse/company_appointments/model/data/DeltaSensitiveData.java
- src/main/java/uk/gov/companieshouse/company_appointments/model/transformer/DeltaOfficerDataTransformer.java
- src/main/java/uk/gov/companieshouse/company_appointments/model/transformer/DeltaSensitiveDataTransformer.java
- src/test/java/uk/gov/companieshouse/company_appointments/model/transformer/DeltaOfficerDataTransformerTest.java
- src/test/java/uk/gov/companieshouse/company_appointments/model/transformer/DeltaSensitiveDataTransformerTest.java
- src/test/java/uk/gov/companieshouse/company_appointments/officerappointments/OfficerAppointmentsMapperTest.java
* Persists boolean address fields with "is_same_as" instead of just "same_as" which comes in in the request body.
[DSND-2067](https://companieshouse.atlassian.net/browse/DSND-2067)
[DSND-2067]: https://companieshouse.atlassian.net/browse/DSND-2067?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DSND-2067: Change name of boolean address fields

- src/main/java/uk/gov/companieshouse/company_appointments/service/CompanyAppointmentFullRecordService.java
- src/test/java/uk/gov/companieshouse/company_appointments/service/CompanyAppointmentFullRecordServiceTest.java
* Removes the transactional annotation from the upsert path and instead adds a compensatory transaction.
* If the call to chs-kafka-api fails during processing of an insert or update
then the document will be removed or reverted back to its original state.
[DSND-2139](https://companieshouse.atlassian.net/browse/DSND-2139)
[DSND-2139]: https://companieshouse.atlassian.net/browse/DSND-2139?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DSND-2139 Compensatory transaction on insert/update

- routes.yaml
* Only calls to /full_record endpoints will be handled by this API version.
* Other endpoints will be handled by v0.1.67 in live.
[DSND-2066](https://companieshouse.atlassian.net/browse/DSND-2066)
[DSND-2066]: https://companieshouse.atlassian.net/browse/DSND-2066?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DSND-2066: Change routes for seeding in live

- terraform/groups/ecs-service/main.tf
- terraform/groups/ecs-service/profiles/live-eu-west-2/live/vars
- terraform/groups/ecs-service/variables.tf
We need to increase the ECS resources due to the intense traffic received by the service in Live.
This PR bumps up the cpu amount for the app and eric container as well as the desired task count.
> feat: bump up app/eric cpus as well as fargate task count for live env

- src/it/java/uk/gov/companieshouse/company_appointments/officerappointments/OfficerAppointmentsControllerITest.java
- src/main/java/uk/gov/companieshouse/company_appointments/officerappointments/FilterService.java
- src/main/java/uk/gov/companieshouse/company_appointments/officerappointments/ItemsPerPageService.java
- src/main/java/uk/gov/companieshouse/company_appointments/officerappointments/OfficerAppointmentsRepository.java
- src/main/java/uk/gov/companieshouse/company_appointments/officerappointments/OfficerAppointmentsRequest.java
- src/main/java/uk/gov/companieshouse/company_appointments/officerappointments/OfficerAppointmentsService.java
- src/test/java/uk/gov/companieshouse/company_appointments/officerappointments/FilterServiceTest.java
- src/test/java/uk/gov/companieshouse/company_appointments/officerappointments/ItemsPerPageServiceTest.java
- src/test/java/uk/gov/companieshouse/company_appointments/officerappointments/OfficerAppointmentsRepositoryITest.java
- src/test/java/uk/gov/companieshouse/company_appointments/officerappointments/OfficerAppointmentsServiceTest.java
- src/test/resources/appointmentdocuments/inactive_officer_appointment.json
- src/test/resources/appointmentdocuments/nat_pre_1992_delta_appointment_document_template.json
- src/test/resources/appointmentdocuments/resigned_officer_appointment.json
* The name, is_corporate_officer and date_of_birth fields are
populated using data from the first chosen officer appointment.
* Previously the first one returned from Mongo, now has been changed
to be the most recently appointed active appointment, if any, or the most recently
appointed resigned or inactive appointment.
[BI-13919](https://companieshouse.atlassian.net/browse/BI-13919)
[BI-13919]: https://companieshouse.atlassian.net/browse/BI-13919?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> BI-13919: Change selection of first officer appointment in list

- src/it/resources/features/upsert_full_record_appointment.feature
- src/main/java/uk/gov/companieshouse/company_appointments/service/CompanyAppointmentFullRecordService.java
- src/test/java/uk/gov/companieshouse/company_appointments/service/CompanyAppointmentFullRecordServiceTest.java
* Removed compensatory transaction for saves
* Modified stale delta checks to allow `delta_at` values on deltas and saved documents to have the same value and still be processed
* Resource changed updates can fail and be retried while leaving updated documents in Mongo
[DSND-3019](https://companieshouse.atlassian.net/browse/DSND-3019)
[DSND-3019]: https://companieshouse.atlassian.net/browse/DSND-3019?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DSND-3019: Change processing order for updates

- pom.xml
- src/it/java/uk/gov/companieshouse/company_appointments/steps/FullRecordAppointmentSteps.java
- src/it/java/uk/gov/companieshouse/company_appointments/tests/AuthenticationInterceptorsITest.java
- src/it/java/uk/gov/companieshouse/company_appointments/tests/CompanyAppointmentControllerITest.java
- src/it/java/uk/gov/companieshouse/company_appointments/tests/CompanyAppointmentFullRecordControllerITest.java
- src/it/java/uk/gov/companieshouse/company_appointments/tests/CompanyAppointmentFullRecordControllerMongoUnavailableITest.java
- src/it/resources/features/delete_full_record_appointment.feature
- src/main/java/uk/gov/companieshouse/company_appointments/controller/CompanyAppointmentFullRecordController.java
- src/main/java/uk/gov/companieshouse/company_appointments/service/CompanyAppointmentFullRecordService.java
- src/main/java/uk/gov/companieshouse/company_appointments/service/DeleteAppointmentService.java
- src/test/java/uk/gov/companieshouse/company_appointments/CompanyAppointmentFullRecordControllerTest.java
- src/test/java/uk/gov/companieshouse/company_appointments/service/CompanyAppointmentFullRecordServiceTest.java
- src/test/java/uk/gov/companieshouse/company_appointments/service/DeleteAppointmentWithRetryServiceTest.java
After updates to the private-api-sdk-java delete resource API, delete offices now include a `delta_at` check to stop stale deltas deleting new documents
[DSND-3111](https://companieshouse.atlassian.net/browse/DSND-3111)
[DSND-3111]: https://companieshouse.atlassian.net/browse/DSND-3111?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DSND-3111: Implements a delete delta with a delta_at check

- src/it/java/uk/gov/companieshouse/company_appointments/officerappointments/OfficerAppointmentsControllerITest.java
- src/main/java/uk/gov/companieshouse/company_appointments/officerappointments/OfficerAppointmentsRepository.java
* Added secondary sort to the other officer appointments latest appointment logic.
* Removed $add_fields from the repository query.
[BI-14441](https://companieshouse.atlassian.net/browse/BI-14441)
[BI-14441]: https://companieshouse.atlassian.net/browse/BI-14441?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> BI-14441: Add secondary sort improvements to other repo call
