src/it/java/uk/gov/companieshouse/company_appointments/CompanyAppointmentControllerITest.java
src/main/java/uk/gov/companieshouse/company_appointments/config/Config.java
src/main/java/uk/gov/companieshouse/company_appointments/interceptor/AuthenticationInterceptor.java
src/test/java/uk/gov/companieshouse/company_appointments/interceptor/AuthenticationInterceptorTest.java

* Verify that API user has authenticated via ERIC.

SAPI-420 add authentication checks

---

Makefile

* Add Makefile target to build a Docker container holding the JAR file that has been built.

Build Docker container

---

src/main/resources/application.properties

* Allow connection properties to be specified with the MongoDB URL

Remove DB name from MongoDB URL

---

src/main/java/uk/gov/companieshouse/company_appointments/CompanyAppointmentController.java
src/main/java/uk/gov/companieshouse/company_appointments/CompanyAppointmentMapper.java
src/main/java/uk/gov/companieshouse/company_appointments/CompanyAppointmentService.java
src/main/java/uk/gov/companieshouse/company_appointments/config/Config.java
src/main/java/uk/gov/companieshouse/company_appointments/interceptor/AuthenticationInterceptor.java
src/main/java/uk/gov/companieshouse/company_appointments/interceptor/RequestLoggingInterceptor.java
src/test/java/uk/gov/companieshouse/company_appointments/interceptor/AuthenticationInterceptorTest.java

Reverts companieshouse/company-appointments.api.ch.gov.uk#8

Revert "Remove structured logging from all classes"

---

pom.xml

Reverts companieshouse/company-appointments.api.ch.gov.uk#7

Revert "Remove structured logging from POM for debugging"

---

Tiltfile
Tiltfile.dev
docker-compose.yml
pom.xml

This is necessary for us to dev the addition of the new endpoint and covers most of DSND-68
Docker CHS PR: https://github.com/companieshouse/docker-chs-development/pull/269

Add jib plugin and tilt files for docker

---

routes.yaml

Added v2 endpoint

---

pom.xml

- TODO: update with actual SDK release version when known
Resolves:
DSND-149
DSND-174

Update POM with pending SDK changes

---

pom.xml

https://companieshouse.atlassian.net/browse/DSND-146

Increasing private java sdk api version

---

src/main/java/uk/gov/companieshouse/company_appointments/config/Config.java

relating to work done in DSND-185

attempt to fix issue where service not starting in e2e

---

src/main/java/uk/gov/companieshouse/company_appointments/config/Config.java
src/main/java/uk/gov/companieshouse/company_appointments/config/LoggingConfig.java
src/main/java/uk/gov/companieshouse/company_appointments/interceptor/RequestLoggingInterceptor.java
src/test/java/uk/gov/companieshouse/company_appointments/config/LoggingConfigTest.java

- move RequestLoggingInterceptor bean to new LoggingConfig class

Try to fix bean dependencies for RequestLoggingInterceptor

---

pom.xml

see officer-delta-api PR: https://github.com/companieshouse/officer-delta-processor/pull/27
DSND-183

New sdk version to include Usual Residential Address

---

pom.xml

Associated with https://github.com/companieshouse/officer-delta-processor/pull/34
DSND-181

Update private sdk version, necessary for secure officer indicator

---

pom.xml

private-sdk PR https://github.com/companieshouse/private-api-sdk-java/pull/122
DSND-208

new sdk has been corrected to use isSecureOfficer

---

src/main/java/uk/gov/companieshouse/company_appointments/model/view/CompanyAppointmentFullRecordView.java
src/test/java/uk/gov/companieshouse/company_appointments/model/view/CompanyAppointmentFullRecordViewTest.java

https://companieshouse.atlassian.net/browse/DSND-303

Adding appointedBefore to CompanyAppointmentFullRecordView

---

pom.xml
src/main/java/uk/gov/companieshouse/company_appointments/CompanyAppointmentFullRecordRepository.java
src/main/java/uk/gov/companieshouse/company_appointments/CompanyAppointmentFullRecordService.java
src/main/java/uk/gov/companieshouse/company_appointments/model/data/AppointmentApiEntity.java
src/test/java/uk/gov/companieshouse/company_appointments/AppointmentApiRepositoryTest.java
src/test/java/uk/gov/companieshouse/company_appointments/CompanyAppointmentFullRecordServiceTest.java

https://companieshouse.atlassian.net/browse/DSND-232

Adding updated object to Appointment and correcting created object.

---

src/main/java/uk/gov/companieshouse/company_appointments/interceptor/FullRecordAuthenticationInterceptor.java
src/test/java/uk/gov/companieshouse/company_appointments/interceptor/FullRecordAuthenticationInterceptorTest.java

Added log to show authentication failure in FullRecordAuthenticationInterceptor and show cause.

Added logging to authentication failure

---

Makefile
pom.xml
src/it/java/uk/gov/companieshouse/company_appointments/AuthenticationInterceptorsITest.java
src/it/java/uk/gov/companieshouse/company_appointments/CompanyAppointmentControllerITest.java
src/main/java/uk/gov/companieshouse/company_appointments/interceptor/AuthenticationInterceptor.java
src/main/java/uk/gov/companieshouse/company_appointments/interceptor/RequestLoggingInterceptor.java

* Use Spring Boot version 2.5 and testcontainers 1.16.
* Fix project Makefile so that integration tests will be run if test-integration target run.
* Tested locally, working.
Resolves:
[BI-9520](https://companieshouse.atlassian.net/browse/BI-9520)

BI-9520 Upgrade project dependencies

---

src/main/resources/application.properties

corresponds with https://github.com/companieshouse/chs-configs/pull/1694

Amend to use LOGLEVEL env value

---

spec/spec.json

https://companieshouse.atlassian.net/browse/DSND-313

Updating swagger spec

---

src/main/java/uk/gov/companieshouse/company_appointments/CompanyAppointmentMapper.java
src/main/java/uk/gov/companieshouse/company_appointments/model/data/ContactDetailsData.java
src/main/java/uk/gov/companieshouse/company_appointments/model/data/OfficerData.java
src/main/java/uk/gov/companieshouse/company_appointments/model/view/CompanyAppointmentView.java
src/main/java/uk/gov/companieshouse/company_appointments/model/view/ContactDetailsView.java
src/test/java/uk/gov/companieshouse/company_appointments/CompanyAppointmentMapperTest.java

add and update models and mappings to handle managing officer details
add tests
Resolves: ROE-176

add and update models and mappings to handle managing officer details

---

src/it/java/uk/gov/companieshouse/company_appointments/AuthenticationInterceptorsITest.java
src/main/java/uk/gov/companieshouse/company_appointments/interceptor/AuthenticationHelperImpl.java

This pr fixes the integration tests while adding to to specifically test the new OAuth2 authentication route. Also included is a fix to stop nullpointer errors in the authenticator helper.
**Required for:**
- DSND-1240

Add/fix integration tests for OAuth2 authentication

---

src/it/java/uk/gov/companieshouse/company_appointments/AuthenticationInterceptorsITest.java

Fix failing integration test adding new privilege

Add sensitive-data to privilege integration test

---

src/it/java/uk/gov/companieshouse/company_appointments/AuthenticationInterceptorsITest.java
src/main/java/uk/gov/companieshouse/company_appointments/interceptor/AuthenticationHelperImpl.java
src/test/java/uk/gov/companieshouse/company_appointments/interceptor/AuthenticationHelperImplTest.java

This pr changes the read protected permission check to use the new hyphenless permission.

Remove hyphen from read protected permission

---

pom.xml

updated java sdk version in the pom file.

updated sdk version in pom

---

src/main/java/uk/gov/companieshouse/company_appointments/model/data/AppointmentApiEntity.java
src/test/java/uk/gov/companieshouse/company_appointments/AppointmentApiRepositoryTest.java
src/test/java/uk/gov/companieshouse/company_appointments/CompanyAppointmentFullRecordServiceTest.java

Added values for officer role sort order

added values for officer role sort order

---

pom.xml
src/main/java/uk/gov/companieshouse/company_appointments/model/view/CompanyAppointmentFullRecordView.java

Added person number to Data API
Integration tests did not need to be changed, since they still work.
Updated Pom.xml file
-DSND-1402

added person number to Data API

---

pom.xml
src/it/java/uk/gov/companieshouse/company_appointments/CompanyAppointmentControllerITest.java
src/it/java/uk/gov/companieshouse/company_appointments/CompanyAppointmentFullRecordControllerITest.java
src/main/java/uk/gov/companieshouse/company_appointments/ApiClientService.java
src/main/java/uk/gov/companieshouse/company_appointments/CompanyAppointmentController.java
src/main/java/uk/gov/companieshouse/company_appointments/CompanyAppointmentMapper.java
src/main/java/uk/gov/companieshouse/company_appointments/CompanyAppointmentService.java
src/main/java/uk/gov/companieshouse/company_appointments/CompanyRegisterService.java
src/main/java/uk/gov/companieshouse/company_appointments/DirectorRoles.java
src/main/java/uk/gov/companieshouse/company_appointments/LlpRoles.java
src/main/java/uk/gov/companieshouse/company_appointments/RoleHelper.java
src/main/java/uk/gov/companieshouse/company_appointments/ServiceUnavailableException.java
src/main/resources/application.properties
src/test/java/uk/gov/companieshouse/company_appointments/CompanyAppointmentControllerTest.java
src/test/java/uk/gov/companieshouse/company_appointments/CompanyAppointmentServiceTest.java
src/test/java/uk/gov/companieshouse/company_appointments/CompanyRegisterServiceTest.java
src/test/java/uk/gov/companieshouse/company_appointments/RoleHelperTest.java

Added register type and register view parameters to LIST_GET for officer delta.
Added register view in AllCompaniesAppointmentsView
Added checks if register is held in Companies House in the CompanyRegisterService and invoked get metrics api and handle api calls.
Added separate classes for the director and llp roles, to be able to get them.
Added a service unavailable exception class.
-DSND-1375

added register type and register view parameters to list_get officer delta

---

src/main/resources/application.properties

Adds jackson ignore null by default to application properties.

ignore null fields

---

src/main/java/uk/gov/companieshouse/company_appointments/model/data/DeltaAppointmentApiEntity.java

Remove if field as it is breaking the mongo loading.

remove extra id field

---

src/it/java/uk/gov/companieshouse/company_appointments/tests/CompanyAppointmentFullRecordControllerITest.java
src/main/java/uk/gov/companieshouse/company_appointments/model/data/DeltaContactDetails.java
src/main/java/uk/gov/companieshouse/company_appointments/model/data/DeltaIdentification.java
src/main/java/uk/gov/companieshouse/company_appointments/model/data/DeltaPrincipalOfficeAddress.java
src/main/java/uk/gov/companieshouse/company_appointments/model/data/DeltaServiceAddress.java
src/main/java/uk/gov/companieshouse/company_appointments/model/data/DeltaUsualResidentialAddress.java
src/test/resources/delta-appointment-data.json

* Added JsonProperty annotation to some database models which are used in the hand crafted response models. These should be removed when the response models get changed to the generated ones.
[DSND-1666](https://companieshouse.atlassian.net/browse/DSND-1666)
[DSND-1666]: https://companieshouse.atlassian.net/browse/DSND-1666?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DSND-1666 Fix full record get response field mapping

---

src/it/java/uk/gov/companieshouse/company_appointments/tests/CompanyAppointmentControllerITest.java
src/main/java/uk/gov/companieshouse/company_appointments/controller/CompanyAppointmentController.java

* Added Location header to PATCH responses for company appointments
* Updated integration tests to check

DSND-1531: Added missing Location header to PATCH company appointments

---

pom.xml
src/test/java/uk/gov/companieshouse/company_appointments/officerappointments/IdentificationMapperTest.java
src/test/java/uk/gov/companieshouse/company_appointments/officerappointments/IdentificationTypeMapperTest.java

* Fix broken unit tests to use correct enum
Resolves [DSND-1708](https://companieshouse.atlassian.net/browse/DSND-1708)
[DSND-1708]: https://companieshouse.atlassian.net/browse/DSND-1708?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DSND-1708 Update private-api-sdk-java version

---

pom.xml
src/test/java/uk/gov/companieshouse/company_appointments/officerappointments/OfficerRoleMapperTest.java

* Version upgrade brings in corrected officer role enum.
[DSND-1721](https://companieshouse.atlassian.net/browse/DSND-1721)
[DSND-1721]: https://companieshouse.atlassian.net/browse/DSND-1721?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DSND-1721: Upgrade private sdk version

---

pom.xml
src/it/java/uk/gov/companieshouse/company_appointments/CucumberFeaturesRunnerITest.java
src/it/java/uk/gov/companieshouse/company_appointments/steps/CommonSteps.java
src/main/java/uk/gov/companieshouse/company_appointments/model/data/DeltaOfficerData.java
src/main/java/uk/gov/companieshouse/company_appointments/model/transformer/DeltaOfficerDataTransformer.java
src/main/java/uk/gov/companieshouse/company_appointments/model/view/CompanyAppointmentFullRecordView.java
src/test/java/uk/gov/companieshouse/company_appointments/model/transformer/DeltaOfficerDataTransformerTest.java
src/test/java/uk/gov/companieshouse/company_appointments/model/view/CompanyAppointmentFullRecordViewTest.java

* Changes appointed_on, appointed_before and resigned_on within DeltaOfficerData to be of type Instant instead of LocalDate.
[DSND-1737](https://companieshouse.atlassian.net/browse/DSND-1737) Main JIRA ticket
[DSND-1789](https://companieshouse.atlassian.net/browse/DSND-1789) Subtask
[DSND-1737]: https://companieshouse.atlassian.net/browse/DSND-1737?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DSND-1789]: https://companieshouse.atlassian.net/browse/DSND-1789?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DSND-1737 Standardise additional dates

---

src/main/java/uk/gov/companieshouse/company_appointments/model/transformer/DeltaOfficerDataTransformer.java
src/test/java/uk/gov/companieshouse/company_appointments/model/transformer/DeltaOfficerDataTransformerTest.java

[DSND-1839](https://companieshouse.atlassian.net/browse/DSND-1839)
[DSND-1839]: https://companieshouse.atlassian.net/browse/DSND-1839?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DSND-1839 Add etag to data field

---

pom.xml
src/test/java/uk/gov/companieshouse/company_appointments/model/transformer/DeltaIdentificationTransformerTest.java

* Brings in a fix for the UK limited company identification type
[DSND-1919](https://companieshouse.atlassian.net/browse/DSND-1919)
[DSND-1919]: https://companieshouse.atlassian.net/browse/DSND-1919?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DSND-1919: Upgrades version of private sdk

---

pom.xml
src/main/java/uk/gov/companieshouse/company_appointments/model/data/DeltaServiceAddress.java
src/main/java/uk/gov/companieshouse/company_appointments/model/transformer/DeltaServiceAddressTransformer.java
src/test/java/uk/gov/companieshouse/company_appointments/model/transformer/DeltaServiceAddressTransformerTest.java

* Update model class with new fields
* Update pom.xml for latest SDK version, for source entity changes
* Update unit test cases
* Locally tested; results are as expected.
Resolves [DSND-1949](https://companieshouse.atlassian.net/browse/DSND-1949) 
[DSND-1949]: https://companieshouse.atlassian.net/browse/DSND-1949?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DSND-1949 Add care_of and po_box fields to DeltaServiceAddress

---

routes.yaml

Resolves [DSND-1452](https://companieshouse.atlassian.net/browse/DSND-1452)
[DSND-1452]: https://companieshouse.atlassian.net/browse/DSND-1452?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DSND-1452 Amend endpoint name change in routes yaml

---

routes.yaml
src/it/java/uk/gov/companieshouse/company_appointments/tests/CompanyAppointmentControllerITest.java
src/main/java/uk/gov/companieshouse/company_appointments/controller/CompanyAppointmentController.java

* Revert the company officers list endpoint to /officers-test

Revert officers list endpoint to officers-test

---

src/it/java/uk/gov/companieshouse/company_appointments/tests/CompanyAppointmentControllerITest.java
src/main/java/uk/gov/companieshouse/company_appointments/repository/CompanyAppointmentRepositoryExtension.java
src/main/java/uk/gov/companieshouse/company_appointments/repository/CompanyAppointmentRepositoryImpl.java
src/main/java/uk/gov/companieshouse/company_appointments/service/CompanyAppointmentService.java
src/test/java/uk/gov/companieshouse/company_appointments/service/CompanyAppointmentServiceTest.java

Fixes bug where active filter was still returning inactive appointments and various edge cases.
Tested locally.
[DSND-1923](https://companieshouse.atlassian.net/browse/DSND-1923)
[DSND-1923]: https://companieshouse.atlassian.net/browse/DSND-1923?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DSND-1923: Fix active filtering returning active appointments

---

routes.yaml
src/it/java/uk/gov/companieshouse/company_appointments/tests/CompanyAppointmentControllerITest.java
src/main/java/uk/gov/companieshouse/company_appointments/controller/CompanyAppointmentController.java

* Change the URI for the company officers list endpoint back to /officers

Change company officers list to /officers

---

src/main/java/uk/gov/companieshouse/company_appointments/model/view/CompanyAppointmentFullRecordView.java
src/main/java/uk/gov/companieshouse/company_appointments/officerappointments/DateOfBirthMapper.java
src/test/java/uk/gov/companieshouse/company_appointments/model/view/CompanyAppointmentFullRecordViewTest.java

* Fixes a null pointer exception bug when sensitive data is null
[DSND-2062](https://companieshouse.atlassian.net/browse/DSND-2062)
[DSND-2062]: https://companieshouse.atlassian.net/browse/DSND-2062?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DSND-2062: Fix failing karate tests when sensitive data null

---

routes.yaml

Reverts companieshouse/company-appointments.api.ch.gov.uk#145
[DSND-2066](https://companieshouse.atlassian.net/browse/DSND-2066)
[DSND-2066]: https://companieshouse.atlassian.net/browse/DSND-2066?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Revert "DSND-2066: Change routes for seeding in live"

---

src/main/java/uk/gov/companieshouse/company_appointments/model/data/DeltaOfficerData.java
src/main/java/uk/gov/companieshouse/company_appointments/model/view/CompanyAppointmentFullRecordView.java
src/test/java/uk/gov/companieshouse/company_appointments/model/view/CompanyAppointmentFullRecordViewTest.java

Add secure_officer boolean and title to the company appointments view.

dact-1483 add secure_officer boolean and title to view

---

src/test/resources/PUT_full_record_request_body_with_empty_locality_fields.json

Fix broken test to enable pipeline to build.

dact-1738 fix broken test

---

pom.xml
src/main/java/uk/gov/companieshouse/company_appointments/model/transformer/DeltaOfficerDataTransformer.java
src/main/java/uk/gov/companieshouse/company_appointments/model/transformer/DeltaSensitiveDataTransformer.java
src/test/java/uk/gov/companieshouse/company_appointments/model/transformer/DeltaOfficerDataTransformerTest.java
src/test/java/uk/gov/companieshouse/company_appointments/model/transformer/DeltaSensitiveDataTransformerTest.java
src/test/resources/PUT_full_record_request_body_with_empty_locality_fields.json

[DSND-2076](https://companieshouse.atlassian.net/browse/DSND-2076)
[DSND-2076]: https://companieshouse.atlassian.net/browse/DSND-2076?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DSND-2076: Update sdk to add "is" to same as fields

---

pom.xml
src/it/java/uk/gov/companieshouse/company_appointments/tests/CompanyAppointmentControllerITest.java
src/it/java/uk/gov/companieshouse/company_appointments/tests/CompanyAppointmentFullRecordControllerITest.java
src/it/java/uk/gov/companieshouse/company_appointments/tests/CompanyAppointmentFullRecordControllerMongoUnavailableITest.java
src/main/java/uk/gov/companieshouse/company_appointments/api/CompanyMetricsApiService.java
src/main/java/uk/gov/companieshouse/company_appointments/controller/CompanyAppointmentController.java
src/main/java/uk/gov/companieshouse/company_appointments/controller/CompanyAppointmentFullRecordController.java
src/main/java/uk/gov/companieshouse/company_appointments/exception/NotFoundException.java
src/main/java/uk/gov/companieshouse/company_appointments/interceptor/AuthenticationInterceptor.java
src/main/java/uk/gov/companieshouse/company_appointments/interceptor/FullRecordAuthenticationInterceptor.java
src/main/java/uk/gov/companieshouse/company_appointments/officerappointments/OfficerAppointmentsController.java
src/main/java/uk/gov/companieshouse/company_appointments/service/CompanyAppointmentFullRecordService.java
src/main/java/uk/gov/companieshouse/company_appointments/service/CompanyAppointmentService.java

Added the officer's internal IDm company name and status to the log map
Reduced log levels to info for non-fatal exceptions
Removed verbose log messages

DSND-2869: Updated structural logging 

---

terraform/groups/ecs-service/profiles/live-eu-west-2/live/vars

* Removed increase in ERIC resources and increased API so they add up to predefined values.
* Increased task count so ERIC has enough connections for the live traffic.
* Values taken from [filing-history-data-api](https://github.com/companieshouse/filing-history-data-api/blob/d8616139d0f5cedf780dedc0b4f3a12127a4f593/terraform/groups/ecs-service/profiles/live-eu-west-2/live/vars#L8)
Unblocks [DSND-2823](https://companieshouse.atlassian.net/browse/DSND-2823)
[DSND-2823]: https://companieshouse.atlassian.net/browse/DSND-2823?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DSND-2823: Increase resources and tasks for live

---

terraform/groups/ecs-service/profiles/live-eu-west-2/live/vars
terraform/groups/ecs-service/variables.tf

[DSND-2823](https://companieshouse.atlassian.net/browse/DSND-2823)
[DSND-2823]: https://companieshouse.atlassian.net/browse/DSND-2823?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DSND-2823: Increase default max tasks

---

src/main/java/uk/gov/companieshouse/company_appointments/config/Config.java
src/main/java/uk/gov/companieshouse/company_appointments/mapper/ResourceChangedRequestMapper.java
src/main/java/uk/gov/companieshouse/company_appointments/util/DateTimeProcessor.java
src/test/java/uk/gov/companieshouse/company_appointments/ResourceChangedRequestMapperTest.java
src/test/java/uk/gov/companieshouse/company_appointments/util/DateTimeProcessorTest.java

[BI-13961](https://companieshouse.atlassian.net/browse/BI-13961)
[BI-13961]: https://companieshouse.atlassian.net/browse/BI-13961?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

BI-13961: Format published at to seconds

---

src/main/java/uk/gov/companieshouse/company_appointments/exception/ServiceUnavailableException.java
src/main/java/uk/gov/companieshouse/company_appointments/service/CompanyAppointmentService.java
src/test/java/uk/gov/companieshouse/company_appointments/service/CompanyAppointmentServiceTest.java

[DSND-3013](https://companieshouse.atlassian.net/browse/DSND-3013)
[DSND-3013]: https://companieshouse.atlassian.net/browse/DSND-3013?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DSND-3013: Improve logging

---

pom.xml
src/it/resources/features/upsert_full_record_appointment.feature
src/main/java/uk/gov/companieshouse/company_appointments/controller/CompanyAppointmentFullRecordController.java
src/main/java/uk/gov/companieshouse/company_appointments/service/CompanyAppointmentFullRecordService.java
src/test/java/uk/gov/companieshouse/company_appointments/CompanyAppointmentFullRecordControllerTest.java
src/test/java/uk/gov/companieshouse/company_appointments/service/CompanyAppointmentFullRecordServiceTest.java

* Fix logging of existing delta on stale delta in upsert
* Throw conflict error on stale delta upsert in service
* Return conflict status on stale delta put in controller
* Add/fix existing tests
* Update pom versions
Resolves [DSND-3193](https://companieshouse.atlassian.net/browse/DSND-3193)
[DSND-3193]: https://companieshouse.atlassian.net/browse/DSND-3193?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DSND-3193: Fix upsert logging on stale delta

---

terraform/groups/ecs-service/profiles/staging-eu-west-2/staging/vars

[DSND-3268](https://companieshouse.atlassian.net/browse/DSND-3268)
[DSND-3268]: https://companieshouse.atlassian.net/browse/DSND-3268?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DSND-3268: Increase staging resource same as live for perf tests

---

pom.xml
src/main/java/uk/gov/companieshouse/company_appointments/mapper/CompanyAppointmentMapper.java
src/test/java/uk/gov/companieshouse/company_appointments/CompanyAppointmentMapperTest.java

This removes the day from the dob when `register_view` is set to True.

GCI-2620: Remove day from dob in registerView officers
